using System.ComponentModel;
using P2XMLEditor.Attributes;

namespace P2XMLEditor.GameData.Templates.Enums;

[TypeConverter(typeof(EnumConverter))]
  public enum InteractType {
    [SerializationData("None")] None,
    [SerializationData("Interact")] Interact,
    [SerializationData("Indoor")] Indoor,
    [SerializationData("Outdoor")] Outdoor,
    [SerializationData("Break")] Break,
    [SerializationData("Keyhole")] Keyhole,
    [SerializationData("Dialog")] Dialog,
    [SerializationData("Trade")] Trade,
    [SerializationData("Loot")] Loot,
    [SerializationData("Autopsy")] Autopsy,
    [SerializationData("OpenDoor")] OpenDoor,
    [SerializationData("CloseDoor")] CloseDoor,
    [SerializationData("Knock")] Knock,
    [SerializationData("Block")] Block,
    [SerializationData("Unblock")] Unblock,
    [SerializationData("Mark")] Mark,
    [SerializationData("Unmark")] Unmark,
    [SerializationData("Collect")] Collect,
    [SerializationData("BreakPicklock")] BreakLockpick,
    [SerializationData("KeyOpening")] KeyOpening,
    [SerializationData("Sleep")] Sleep,
    [SerializationData("Heal")] Heal,
    [SerializationData("Hydrant")] Hydrant,
    [SerializationData("HydrantNoBottles")] HydrantNoBottles,
    [SerializationData("TradeImpossible")] TradeImpossible,
    [SerializationData("Repair")] Repair,
    [SerializationData("AskForRepair")] AskForRepair,
    [SerializationData("Upgrade")] Upgrade,
    [SerializationData("Broken")] Broken,
    [SerializationData("Empty")] Empty,
    [SerializationData("IconNormal")] IconNormal,
    [SerializationData("IconLocked")] IconLocked,
    [SerializationData("IconBlocked")] IconBlocked,
    [SerializationData("Drink")] Drink,
    [SerializationData("BreakPicklockNoPick")] BreakLockpickNoLockpick,
    [SerializationData("Prophylaxis")] Prophylaxis,
    [SerializationData("HealEarthNoBlood")] HealEarthNoBlood,
    [SerializationData("FastTravel")] FastTravel,
    [SerializationData("Surgery")] Surgery,
    [SerializationData("LightCandleNoMatches")] LightCandleNoMatches,
    [SerializationData("TheaterAfisha")] TheaterAfisha,
    [SerializationData("HealEarthExausted")] HealEarthExhausted,
    [SerializationData("CraftTable")] CraftTable,
  }