namespace P2XMLEditor.GameData.Templates.Enums;

using System.ComponentModel;
using Attributes;

[TypeConverter(typeof(EnumConverter))]
public enum StorableGroup {
    [SerializationData("None")] None,
    [SerializationData("Weapons_Primary")] Weapons_Primary,
    [SerializationData("Clothes_Ammo")] Clothes_Ammo,
    [SerializationData("Autopsy_Instrument_Head")] Autopsy_Instrument_Head,
    [SerializationData("Clothes_Head")] Clothes_Head,
    [SerializationData("Clothes_Arms")] Clothes_Arms,
    [SerializationData("Clothes_Body")] Clothes_Body,
    [SerializationData("Clothes_Feet")] Clothes_Feet,
    [SerializationData("Usable")] Usable,
    [SerializationData("Quest")] Quest,
    [SerializationData("Weapons_Secondary")] Weapons_Secondary,
    [SerializationData("Autopsy_Instrument_Chest")] Autopsy_Instrument_Chest,
    [SerializationData("Autopsy_Instrument_Stomach")] Autopsy_Instrument_Stomach,
    [SerializationData("Loot_Instrument_Lockpick")] Loot_Instrument_Lockpick,
    [SerializationData("Autopsy_Head")] Autopsy_Head,
    [SerializationData("Autopsy_Chest")] Autopsy_Chest,
    [SerializationData("Autopsy_Stomach")] Autopsy_Stomach,
    [SerializationData("Craft_Grass")] Craft_Grass,
    [SerializationData("Craft_Liquid")] Craft_Liquid,
    [SerializationData("Craft_Mixture")] Craft_Mixture,
    [SerializationData("Craft_Organ")] Craft_Organ,
    [SerializationData("Craft_Medicament")] Craft_Medicament,
    [SerializationData("Lockpick_Container")] Lockpick_Container,
    [SerializationData("Lockpick_Door")] Lockpick_Door,
    [SerializationData("Weapons_Hands")] Weapons_Hands,
    [SerializationData("Autopsy_Blood")] Autopsy_Blood,
    [SerializationData("Autopsy_Instrument_Bottle")] Autopsy_Instrument_Bottle,
    [SerializationData("Money")] Money,
    [SerializationData("Disease")] Disease,
    [SerializationData("Symptom")] Symptom,
    [SerializationData("Key")] Key,
    [SerializationData("Ammo_Revolver")] Ammo_Revolver,
    [SerializationData("Ammo_Rifle")] Ammo_Rifle,
    [SerializationData("Ammo_Shotgun")] Ammo_Shotgun,
    [SerializationData("Pharmacy_Medicament")] Pharmacy_Medicament,
    [SerializationData("Diagnostic")] Diagnostic,
    [SerializationData("Antibiotic")] Antibiotic,
    [SerializationData("Painkiller")] Painkiller,
    [SerializationData("Fuel_Lamp")] Fuel_Lamp,
    [SerializationData("ImmuneBooster")] ImmuneBooster,
    [SerializationData("Weapons_Lamp")] Weapons_Lamp,
    [SerializationData("Weapons_Npc")] Weapons_Npc,
    [SerializationData("Chalk")] Chalk,
    [SerializationData("Plague_Map")] Plague_Map,
    [SerializationData("Miracle")] Miracle,
    [SerializationData("Bottled_Liquid")] Bottled_Liquid
}